#
# Leroy-Automation LT200 PXA270 Support
#
# Copyright (C) 2010 Marek Vasut <marek.vasut@gmail.com>
# Copyright (C) 2017 David Pierret <david.pierret@gmail.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= lt200_pxa270.o
